# Generated by Django 3.2.23 on 2023-12-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='شماره تلفن'),
        ),
    ]
