# Generated by Django 3.2.23 on 2023-12-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_otp',
            name='token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
