# Generated by Django 3.2.23 on 2024-01-12 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
    ]
