# Generated by Django 3.2.23 on 2024-01-06 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_discountcodee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiscountCodee',
            new_name='DiscountCode',
        ),
    ]
