# Generated by Django 3.2.23 on 2024-01-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_rename_discountcodee_discountcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
